version: '3'

services:
  redis:
    image: redis:5.0.9
    networks:
      - app-python
  web:
    build: .
    environment:
        - ENVIRONMENT=DEV
        - HOST=redis
        - PORT=8000
        - REDIS_HOST=
        - REDIS_PORT=6379
        - REDIS_DB=0
    networks:
      - app-python
    ports:
      - "8000:8000"
    depends_on:
      - redis

networks:
   app-python: