version: "3"
services:
  web: 
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=DEV
       - HOST=localhost
       - PORT=8000
       - REDIS_PORT=6379
       - REDIS_DB=0
    networks:
      - app-python
  redis:
    image: redis
    networks:
      - app-python

networks:
  app-python:


  